# Generated by Django 3.2.12 on 2022-03-15 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuck_name', models.CharField(max_length=20)),
                ('url_git', models.URLField()),
                ('authors', models.ManyToManyField(to='main.Users')),
            ],
        ),
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('data_create', models.DateTimeField(default=datetime.datetime(2022, 3, 15, 18, 26, 43, 522760, tzinfo=utc))),
                ('data_edit', models.DateTimeField(default=None, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('author', models.OneToOneField(default='[Fuck] - Автор удален!', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.users')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.projects')),
            ],
        ),
    ]
