# Generated by Django 3.2.12 on 2022-03-15 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
