# Generated by Django 3.2.12 on 2022-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_alter_todo_data_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.TextField(),
        ),
    ]
