# Generated by Django 3.2.12 on 2022-03-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('Project', '0003_auto_20220315_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='main.Users'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.OneToOneField(default='[Fuck] - Автор удален!', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to='main.users'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
